### ISSUE TITLE
Outdated code in repl.R

### ISSUE THREAD

**Issue by deepayan** [ltierney/repl#1]
Some parts that are outdated:

- `eval.with.vis()` no longer exists.
- `assign("last.warning", new, baseenv())` no longer works
- Similarly `assignInNamespace(".Last.expression", expr, "base")`
- `assignInNamespace(".Last.value", result$value, "base")` also doesn't seem to work, though not quite as straightforwardly

**Comment by ltierney** [comment]
I think I've 'fixed' these. For `.Last.value` , `.last.warning`, and history recording this means disabling them for now since they would really need some internal support.
